### ISSUE TITLE
Compatible with  Arduino Nano Every 4808 China clone?

### ISSUE THREAD

**Issue by fry2k** [DecksLabs/every-culfw#3]
Hello,

my nano cul is not working because of the memory limitations with the package size of my meters. At wmbusmeters this project here is recommended and I want to try this.

I have seen that a china clone of the Arduino Nano Every exists which uses the chip 4808 instead of 4809. Is this hardware supported by this project? Maybe someone tried it already.

Sorry for opening an issue for that question.

**Comment by DecksLabs** [comment]
Hi,
I haven't tried with the clone, but by looking at the datasheet it seems that it should work out of the box.
-------- Oryginalna wiadomość --------28.11.2024 18:08, Martin Wagner  napisał(a):
Hello,
my nano cul is not working because of the memory limitations with the package size of my meters. At wmbusmeters this project here is recommended and I want to try this.
I have seen that a china clone of the Arduino Nano Every exists which uses the chip 4808 instead of 4809. Is this hardware supported by this project? Maybe someone tried it already.
Sorry for opening an issue for that question.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/DecksLabs/every-culfw/issues/3",
"url": "https://github.com/DecksLabs/every-culfw/issues/3",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by fry2k** [comment]
Thanks a lot for the fast reply. Going to try it. I ordered now such a clone and keep the thread updated when it arrived.

**Comment by fry2k** [comment]
I received now the 4808 and flashed the firmware. That was successful. I changed the avrdude parameter -p to atmega4808 at the flash.sh file:

```
Using Port                    : /dev/ttyUSB0
         Using Programmer              : jtag2updi
         Overriding Baud Rate          : 115200
JTAG ICE mkII sign-on message:
Communications protocol version: 1
M_MCU:
  boot-loader FW version:        1
  firmware version:              6.00
  hardware version:              1
S_MCU:
  boot-loader FW version:        1
  firmware version:              6.00
  hardware version:              1
Serial number:                   0a:0b:0c:0d:0e:0f
Device ID:                       Thinary mkII
         AVR Part                      : ATmega4808
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         Serial program mode           : yes
         Parallel program mode         : yes
         Memory Detail                 :

                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
           prodsig                 0     0     0    0 no         61   61      0     0     0 0x00 0x00
           fuses                   0     0     0    0 no          9    1      0     0     0 0x00 0x00
           fuse0                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse1                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse2                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse4                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse5                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse6                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse7                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse8                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           lock                    0     0     0    0 no          1    1      0     0     0 0x00 0x00
           data                    0     0     0    0 no          0    1      0     0     0 0x00 0x00
           usersig                 0     0     0    0 no         64   64      0     0     0 0x00 0x00
           flash                   0     0     0    0 no      49152  128      0     0     0 0x00 0x00
           eeprom                  0     0     0    0 no        256   64      0     0     0 0x00 0x00

         Programmer Type : JTAGMKII_PDI
         Description     : JTAGv2 to UPDI bridge
         M_MCU HW version: 1
         M_MCU FW version: 6.00
         S_MCU HW version: 1
         S_MCU FW version: 6.00
         Serial number   : 0a:0b:0c:0d:0e:0f
         Vtarget         : 5.0 V

avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9650 (probably m4808)
avrdude: erasing chip
avrdude: reading input file nanoCUL.hex for flash
         with 13494 bytes in 1 section within [0, 0x34b5]
         using 106 pages and 74 pad bytes
avrdude: writing 13494 bytes flash ...

Writing | ################################################## | 100% 3.88 s 

avrdude: 13494 bytes of flash written
avrdude: verifying flash memory against nanoCUL.hex

Reading | ################################################## | 100% 2.70 s 

avrdude: 13494 bytes of flash verified
avrdude: reading input file nanoCUL.fuse.bin for fuses
         with 9 bytes in 1 section within [0, 8]
avrdude: writing 9 bytes fuses ...
avrdude: 9 bytes of fuses written
avrdude: verifying fuses memory against nanoCUL.fuse.bin
avrdude: 9 bytes of fuses verified

avrdude done.  Thank you.
```

When I call wmbusmeters no cul device is found:
wmbusmeters --debug --logtelegrams --verbose /dev/ttyUSB0:cul:t1

```
(wmbusmeters) version: 1.18.0
(config) using device: /dev/ttyUSB0:cul:t1 
(config) number of meters: 0
(lookup) with file/hex "/dev/ttyUSB0" cul
(serial) check if /dev/ttyUSB0 can be accessed
(serial) tty /dev/ttyUSB0 can be accessed
(serial) EVENT thread interrupted
(serial) before config: /dev/ttyUSB0 speed(B38400) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS)
(serial) after config:  /dev/ttyUSB0 speed(B38400) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS)
(serialtty) opened /dev/ttyUSB0 fd 3 (detect cul)
(serial /dev/ttyUSB0) sent "560D0A"
(serial) EVENT thread interrupted
(serial) received binary ""
(cul) probe response ""
(serial /dev/ttyUSB0) sent "560D0A"
(serial) EVENT thread interrupted
(serial) received binary ""
(cul) probe response ""
(serial /dev/ttyUSB0) sent "560D0A"
(serial) EVENT thread interrupted
(serial) received binary ""
(cul) probe response ""
(serialtty) closed /dev/ttyUSB0 (detect cul)
(cul) are you there? no
Expected cul on /dev/ttyUSB0 but did not find it! Ignoring tty!
(serial) EVENT thread interrupted
(verbose) ignoring device t1
No wmbus device detected, waiting for a device to be plugged in.
(shell) exec (capture output) "/bin/pidof"
(shell) arg "wmbusmetersd"
(shell) output: >>><<<
(serial) EVENT thread interrupted
(shell) return code 1
(shell) 867 exited
(shell) exec (capture output) "/bin/pidof"
(shell) arg "wmbusmeters"
(shell) output: >>>864
<<<
(serial) EVENT thread interrupted
(shell) return code 0
(shell) 868 exited
(serial) registered regular callback HOT_PLUG_DETECTOR(0) every 2 seconds
No meters configured. Printing id:s of all telegrams heard!
(serial) waiting for stop
(serial) EVENT thread interrupted
(serial) TIMER thread interrupted
^C(serial) stopping manager
(serial) EVENT thread interrupted
(serial) event loop stopped!
(serial) TIMER thread interrupted
```

Any ideas what I could try?

**Comment by DecksLabs** [comment]
Hi,
I ordered one myself. I wanted second receiver anyway :) I'll be able to say something something more in a couple of days.
I assume ttyUSB0 is correct device?

-------- Oryginalna wiadomość --------7.12.2024 21:53, Martin Wagner  napisał(a):
I received now the 4808 and flashed the firmware. That was successful. I changed the avrdude parameter -p to atmega4808 at the flash.sh file:
Using Port                    : /dev/ttyUSB0
         Using Programmer              : jtag2updi
         Overriding Baud Rate          : 115200
JTAG ICE mkII sign-on message:
Communications protocol version: 1
M_MCU:
  boot-loader FW version:        1
  firmware version:              6.00
  hardware version:              1
S_MCU:
  boot-loader FW version:        1
  firmware version:              6.00
  hardware version:              1
Serial number:                   0a:0b:0c:0d:0e:0f
Device ID:                       Thinary mkII
         AVR Part                      : ATmega4808
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         Serial program mode           : yes
         Parallel program mode         : yes
         Memory Detail                 :

                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
           prodsig                 0     0     0    0 no         61   61      0     0     0 0x00 0x00
           fuses                   0     0     0    0 no          9    1      0     0     0 0x00 0x00
           fuse0                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse1                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse2                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse4                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse5                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse6                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse7                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse8                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
           lock                    0     0     0    0 no          1    1      0     0     0 0x00 0x00
           data                    0     0     0    0 no          0    1      0     0     0 0x00 0x00
           usersig                 0     0     0    0 no         64   64      0     0     0 0x00 0x00
           flash                   0     0     0    0 no      49152  128      0     0     0 0x00 0x00
           eeprom                  0     0     0    0 no        256   64      0     0     0 0x00 0x00

         Programmer Type : JTAGMKII_PDI
         Description     : JTAGv2 to UPDI bridge
         M_MCU HW version: 1
         M_MCU FW version: 6.00
         S_MCU HW version: 1
         S_MCU FW version: 6.00
         Serial number   : 0a:0b:0c:0d:0e:0f
         Vtarget         : 5.0 V

avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9650 (probably m4808)
avrdude: erasing chip
avrdude: reading input file nanoCUL.hex for flash
         with 13494 bytes in 1 section within [0, 0x34b5]
         using 106 pages and 74 pad bytes
avrdude: writing 13494 bytes flash ...

Writing | ################################################## | 100% 3.88 s

avrdude: 13494 bytes of flash written
avrdude: verifying flash memory against nanoCUL.hex

Reading | ################################################## | 100% 2.70 s

avrdude: 13494 bytes of flash verified
avrdude: reading input file nanoCUL.fuse.bin for fuses
         with 9 bytes in 1 section within [0, 8]
avrdude: writing 9 bytes fuses ...
avrdude: 9 bytes of fuses written
avrdude: verifying fuses memory against nanoCUL.fuse.bin
avrdude: 9 bytes of fuses verified

avrdude done.  Thank you.

When I call wmbusmeters no cul device is found:
wmbusmeters --debug --logtelegrams --verbose /dev/ttyUSB0:cul:t1
(wmbusmeters) version: 1.18.0
(config) using device: /dev/ttyUSB0:cul:t1
(config) number of meters: 0
(lookup) with file/hex "/dev/ttyUSB0" cul
(serial) check if /dev/ttyUSB0 can be accessed
(serial) tty /dev/ttyUSB0 can be accessed
(serial) EVENT thread interrupted
(serial) before config: /dev/ttyUSB0 speed(B38400) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS)
(serial) after config:  /dev/ttyUSB0 speed(B38400) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS)
(serialtty) opened /dev/ttyUSB0 fd 3 (detect cul)
(serial /dev/ttyUSB0) sent "560D0A"
(serial) EVENT thread interrupted
(serial) received binary ""
(cul) probe response ""
(serial /dev/ttyUSB0) sent "560D0A"
(serial) EVENT thread interrupted
(serial) received binary ""
(cul) probe response ""
(serial /dev/ttyUSB0) sent "560D0A"
(serial) EVENT thread interrupted
(serial) received binary ""
(cul) probe response ""
(serialtty) closed /dev/ttyUSB0 (detect cul)
(cul) are you there? no
Expected cul on /dev/ttyUSB0 but did not find it! Ignoring tty!
(serial) EVENT thread interrupted
(verbose) ignoring device t1
No wmbus device detected, waiting for a device to be plugged in.
(shell) exec (capture output) "/bin/pidof"
(shell) arg "wmbusmetersd"
(shell) output: >>><<<
(serial) EVENT thread interrupted
(shell) return code 1
(shell) 867 exited
(shell) exec (capture output) "/bin/pidof"
(shell) arg "wmbusmeters"
(shell) output: >>>864
<<<
(serial) EVENT thread interrupted
(shell) return code 0
(shell) 868 exited
(serial) registered regular callback HOT_PLUG_DETECTOR(0) every 2 seconds
No meters configured. Printing id:s of all telegrams heard!
(serial) waiting for stop
(serial) EVENT thread interrupted
(serial) TIMER thread interrupted
^C(serial) stopping manager
(serial) EVENT thread interrupted
(serial) event loop stopped!
(serial) TIMER thread interrupted

Any ideas what I could try?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/DecksLabs/every-culfw/issues/3#issuecomment-2525307321",
"url": "https://github.com/DecksLabs/every-culfw/issues/3#issuecomment-2525307321",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DecksLabs** [comment]
@fry2k 
Hi, keeping you updated. Received my sample of Every clone and started digging into it. Looks like it's not pin-compatible outside of the Arduino environment.
There are adjustments to pin configurations needed, I'll provide code & binary in the following days.

**Comment by fry2k** [comment]
@DecksLabs 
Awesome. Thanks a lot! Let me know if there is anything I can help you with.

**Comment by DecksLabs** [comment]
@fry2k 
can you try this: [everyCUL_4808.zip](https://github.com/user-attachments/files/18223479/everyCUL_4808.zip)? I've remapped pins in firmware to match the chinese Nano Every. After flashing with those files my unit is correctly detected by wmbusmeters but it doesn't receive any telegrams and now I'm not sure if my antenna is bad or there is still something to be done in SW :(

According to datasheet of atmega 4808/9 it's the same thing except for 4808 having less pins and one or two peripherals less (not used by nanocul anyway) so this should work without any other modifications.

**Comment by fry2k** [comment]
@DecksLabs same for me. I flashed the version and the cul is now correct detected by wmbusmeters. I also don't see any telegrams.

I have my setup at a perforated grid plate and just changed the 4808 with the arduino nano I tried first. And with that I receive telegrams. So I'm pretty sure that my CC1101 is working fine and the cabling is right.

I use the cheap 868 MHz variant which looks like that one: 
https://github.com/DecksLabs/every-culfw/blob/main/docs/top.png

**Comment by DecksLabs** [comment]
Thank you for your quick feedback :) I need to check further then. Expect something after Christmas time once I find some free time.

Merry Christmas!


poniedziałek, 23 grudnia 2024 10:44, Martin Wagner ***@***.***> napisał(a):

**Comment by DecksLabs** [comment]
@fry2k 
Enjoy: [everyCUL_4808_v2.zip](https://github.com/user-attachments/files/18233818/everyCUL_4808_v2.zip)
![image](https://github.com/user-attachments/assets/37e1515b-d15d-44f1-aba7-c738a72648a7)
:)

**Comment by fry2k** [comment]
@DecksLabs thank you so much. I receive now telegrams and can start with the integration into my home automation.
Just out of curiosity: what was the missing additional to the port mapping?

I wish you a merry Christmas!

**Comment by DecksLabs** [comment]
@fry2k While changing the pin assignements I missed pin that handles GDO2 from cc1101 module. I must have been in a hurry :)
